### ISSUE TITLE
Want to have a talk

### ISSUE THREAD

**Issue by anshmishra010** [kartikey54/VaccineAvailabilityNotifier#1]
Kartikey , I want to ask something related to this project

**Comment by kartikey54** [comment]
yes, what's up? 

> Kartikey , I want to ask something related to this project

**Comment by anshmishra010** [comment]
@kartikey54 As I am highly interested in this project , but I don't want to copy it

**Comment by anshmishra010** [comment]
So can you explain a bit more about on google meet , if possible ?

**Comment by anshmishra010** [comment]
What you say ? @kartikey54

**Comment by kartikey54** [comment]
Sorry, I'm not available right now for a google meet, we can do it sometime next week maybe 
I'll add a summary here so that everybody interested can check it: 

The project works by polling the CoWin API (documentation: https://apisetu.gov.in/public/api/cowin)

An API is available in the aarogya setu system to check for the availability of the vaccine in a pin code for a specified date. 

The script fires 10 API calls every minute (this is done through node-cron), for fetching the availability for the next 10 days. 
The result is then filtered to check for eligibility based on the age. 
If slots are available, the script sends an email to the specified email id through the nodeMailer module. 

References:
https://www.npmjs.com/package/node-cron
https://www.npmjs.com/package/nodemailer
https://www.npmjs.com/package/axios

**Comment by anshmishra010** [comment]
Okay thankyou for the references

**Comment by anshmishra010** [comment]
@kartikey54  By the way what's that "APPLICATION_PASSWORD" in .env ?
Like I didn't got any password .
And for what it being used ?

**Comment by kartikey54** [comment]
> @kartikey54 By the way what's that "APPLICATION_PASSWORD" in .env ?
> Like I didn't got any password .
> And for what it being used ?

You can generate one. See: https://support.google.com/accounts/answer/185833?p=InvalidSecondFactor&visit_id=637554658548216477-2576856839&rd=1
